painstaking debuggin the whole day: after much grief I fixed it:
When the minuit function returns an array it somehow seems to fuck up the rest of numpy. it gave a very unhelpful stack trace problem:

TypeError                                 Traceback (most recent call last)

/Users/wkerzend/tmp/SN1006/weird_error.py in <module>()
      7 fmin = specGrid.getMinuit(sun)
      8 fmin.values.update({'feh':0.0, 'teff':5780., 'logg':4.5})
----> 9 fmin.simplex()
     10
     11

/Users/wkerzend/scripts/python/pyspecgrid/specgrid.py in __call__(self, *args)
    181         else:
    182             #pdb.set_trace()

--> 183             gridSpec = self.specGrid.getSpec(*args)
    184             gridSpec = gridSpec.interpolate(sampleSpec.wave)
    185

/Users/wkerzend/scripts/python/pyspecgrid/specgrid.py in getSpec(self, *args)
    282         return self.interpGrid(args)
    283     def getSpec(self, *args):
--> 284         return oned.onedspec(self.wave, self.interpGrid(args), mode='waveflux')
    285
    286     def fitChiSq(self, sampleSpec, returnChiSq=False, priors = None):

/Library/Python/2.6/site-packages/scipy/interpolate/interpnd.so in interpnd.NDInterpolatorBase.__call__ (scipy/interpolate/interpnd.c:1896)()
    118
    119
--> 120
    121
    122

/Library/Python/2.6/site-packages/scipy/interpolate/interpnd.so in interpnd._ndim_coords_from_arrays (scipy/interpolate/interpnd.c:2145)()
    140
    141
--> 142
    143
    144

/Library/Python/2.6/site-packages/numpy/lib/stride_tricks.pyc in broadcast_arrays(*args)
     67
     68     """
---> 69     args = map(np.asarray, args)
     70     shapes = [x.shape for x in args]
     71     if len(set(shapes)) == 1:

/Library/Python/2.6/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    233
    234     """
--> 235     return array(a, dtype, copy=False, order=order)
    236
    237 def asanyarray(a, dtype=None, order=None):

TypeError: only length-1 arrays can be converted to Python scalars
WARNING: Failure executing file: <weird_error.py>

---------
a was a normal float and it would work in debug mode. I don't know why, but returning a float works fine.